baseURL = 'https://liminalnegativespace.github.io/blog'
languageCode = 'en-us'
title = 'Liminal Negative Space'
theme = 'hugo-book'

disqusShortname = 'liminal-negative-space'

staticDir = ['static']

# Book configuration
disablePathToLower = true
enableGitInfo = false

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
    unsafe = true

[markup.tableOfContents]
    startLevel = 1

[params]
# (Optional, default light) Sets color theme: light, dark or auto.
# Theme 'auto' switches between dark and light modes based on browser/os preferences
    BookTheme = 'light'
    BookMenuBundle = '/menu'

    recentPosts = 5

    # exclude from navigation
    excludeFromNav = [
        'about',
    ]
