baseURL = 'https://liminalnegativespace.github.io/blog'
languageCode = 'en-us'
title = 'Negative Space'
theme = 'hugo-book'

disqusShortname = 'negativespace-1'

# Book configuration
disablePathToLower = true
enableGitInfo = false

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
    unsafe = true

[markup.tableOfContents]
    startLevel = 1

[params]
# (Optional, default light) Sets color theme: light, dark or auto.
# Theme 'auto' switches between dark and light modes based on browser/os preferences
    BookTheme = 'dark'
    BookMenuBundle = '/menu'
